AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  PrismaVPCKiller: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              AWS:
                "arn:aws:iam::907984961736:root"
            Action: 
              - "sts:AssumeRole"
      RoleName: "Prisma_VPC_Term_Role"
      Path: "/"
  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "VPCKiller"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "ec2:Describe*"
              - "ec2:DeleteSecurityGroup"
              - "ec2:DeleteSubnet"
              - "ec2:DeleteVpc"
              - "ec2:DeleteInternetGateway"
              - "ec2:TerminateInstances"
              - "ec2:DetachInternetGateway"
            Resource: "*"
          - 
            Effect: "Deny"
            Action: 
              - "ec2:Delete*"
              - "ec2:TerminateInstances"
              - "ec2:DetachInternetGateway"
            Resource: "*"
            Condition: 
              StringEquals:
                "aws:RequestedRegion": 
                  - "us-east-1"
      Roles: 
        - 
          Ref: "PrismaVPCKiller"
